---
- hosts: server2.abc.com
  remote_user: test1
  become: true
 #gather_facts: false
  tasks:
     - name: install httpd package
       command: yum install httpd -y
     - name: copy index.html
       shell: echo "testing shell command" > /var/www/html/index.html
     - name: start the httpd service
       raw: systemctl start httpd
     - name: execute the script
       script: ./xyz.sh

