---
- hosts: webserver
  remote_user: test1
  become: true
 #gather_facts: false
  tasks:
     - name: install httpd package
       yum: name=httpd state=installed
       tags:
        - install
     - name: copy index.html
       copy: src=index.html dest=/var/www/html/index.html
       tags:
        - copy
     - name: start the httpd service
       service: name=httpd state=started
       tags:
        - service
