---
- hosts: webserver
  remote_user: test1
  become: true
 #gather_facts: false
  tasks:
     - name: install httpd package
       yum: name=httpd state=installed
     - name: copy index.html
       copy: src=index.html dest=/var/www/html/index.html
     - name: start the httpd service
       service: name=httpd state=started
     - name: copy xyz.j2
       template: src=xyz.j2 dest=/etc/xyz
