---
- hosts: webserver
  remote_user: test1
  become: true
 #gather_facts: false
  tasks:
     - name: install httpd package
       yum: name=httpd state=installed
     - name: copy index.html in {{path}}
       copy: src=index.html dest={{path}}
     - name: start the httpd service
       service: name=httpd state=started
