---
# tasks file for webserver
- name: install httpd package
  yum: name=httpd state=installed
- name: copy index.html
  copy: src=index.html dest=/var/www/html/index.html
 # nofity: restart httpd service
- name: start httpd service
  service: name=httpd state=started
